/** Defines the meta object in the generator config */
export interface DataGeneratorConfigMetaInterface {
  /** The name of the test case */
  testcaseName: string

  /** The name of the table this test case was generated from . (Only if the test case was generated by a table) */
  tableName?: string

  /** The name of the filed in the table this test case was generated from . (Only if the test case was generated by a table) */
  fieldName?: string
}
